/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BackEnd.Client.EventHandling;
import UserInterface.components.ContactComponent;
import UserInterface.components.MessageLabel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JTextField;
import jiconfont.icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author gauravpunjabi
 */
public class ChatFrame extends javax.swing.JFrame implements Constants{

    /**
     * Creates new form MainFrame
     */
    public ChatFrame() {
        initComponents();
        System.out.println("Please enter your name : ");
        this.name = new Scanner(System.in).nextLine();
        customInitComponents();
    }
    private void customInitComponents() {
        setBounds(0,0,1300,799);
        this.setShape(new RoundRectangle2D.Double(0,0,this.getWidth(),this.getHeight(),20,20));
        this.setLocationRelativeTo(null);
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        this.jlClose.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.ARROW_FORWARD, 40, new Color(95,224,212)));
        this.eventHandling = new EventHandling(this);
        this.jpChat.setBackground(CHAT_COLOR_BACKGROUND);
        this.jtfMessage.setBackground(CHAT_COLOR_BACKGROUND);
        this.jpMessages.setBackground(CHAT_COLOR_BACKGROUND);
        this.jpContacts.setBounds(0,0,424,820);
        this.getContentPane().setBackground(new Color(61,90,128).darker());
        this.jpContacts.setBackground(new Color(61,90,128).darker());
        addListeners();
        
    }
    private void addListeners() {
        jtfMessage.addActionListener(eventHandling);
    }
    public void removeAllMessages() {
        this.jpMessages.removeAll();
    }
    public void showMessages(ArrayList<MessageLabel> messages) {
        for(int i=0,y=20;i<messages.size();i++,y+=50) {
            jpMessages.add(messages.get(i));
            if(messages.get(i).isSender()) 
                messages.get(i).setBounds(jpMessages.getWidth() - 20 - messages.get(i).getPreferredSize().width, y, messages.get(i).getPreferredSize().width, messages.get(i).getPreferredSize().height);
            else
                messages.get(i).setBounds(10, y, messages.get(i).getPreferredSize().width, messages.get(i).getPreferredSize().height);
        }
        jpMessages.setPreferredSize(new Dimension(jpMessages.getWidth(),messages.size()*50));
        this.jpMessages.validate();
    }
    public void showContacts(ArrayList<ContactComponent> contacts) {
        for(int i=0,y=0;i<contacts.size();i++,y+=102) {
            contacts.get(i).setBounds(0,y,424,102);
            contacts.get(i).addMouseListener(eventHandling);
            this.jpContacts.add(contacts.get(i));
            contacts.get(i).setVisible(true);
        }
        jpContacts.setPreferredSize(new Dimension(424,contacts.size() * 102));
    }
    public void setReceiver(String name) {
        this.jlReceiver.setText(name);
    }
    public JTextField getMessageTextField() { return this.jtfMessage; }
    public String getName() { return this.name; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpChat = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(this.getBackground());
                g.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            }
        };
        jtfMessage = new javax.swing.JTextField()
        ;
        jspMessages = new javax.swing.JScrollPane();
        jpMessages = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlDP = new javax.swing.JLabel(){
            @Override
            protected void paintComponent(Graphics g)
            {
                g.setColor(Color.WHITE);
                g.drawOval(5, 5, this.getWidth() - 10, this.getHeight() - 10);
            }
        };
        jlReceiver = new javax.swing.JLabel();
        jlStatus = new javax.swing.JLabel();
        jlClose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpContacts = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jpChat.setBackground(new java.awt.Color(51, 55, 69));
        jpChat.setLayout(null);

        jtfMessage.setBackground(new java.awt.Color(242, 245, 234));
        jtfMessage.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jtfMessage.setForeground(new java.awt.Color(255, 255, 255));
        jtfMessage.setText("Enter your Message here : ");
        jtfMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtfMessage.setCaretColor(new java.awt.Color(255, 255, 255));
        jtfMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMessageActionPerformed(evt);
            }
        });
        jpChat.add(jtfMessage);
        jtfMessage.setBounds(20, 740, 780, 40);

        jspMessages.setBackground(new java.awt.Color(51, 55, 69));
        jspMessages.setBorder(null);
        jspMessages.setForeground(new java.awt.Color(51, 55, 69));
        jspMessages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpMessages.setBackground(new java.awt.Color(51, 55, 69));
        jpMessages.setForeground(new java.awt.Color(51, 255, 255));
        jpMessages.setLayout(null);
        jspMessages.setViewportView(jpMessages);

        jpChat.add(jspMessages);
        jspMessages.setBounds(0, 60, 880, 660);

        jPanel1.setBackground(new java.awt.Color(34, 61, 95));
        jPanel1.setLayout(null);
        jPanel1.add(jlDP);
        jlDP.setBounds(10, 0, 60, 60);

        jlReceiver.setFont(new java.awt.Font("Raleway", 0, 19)); // NOI18N
        jlReceiver.setForeground(new java.awt.Color(255, 255, 255));
        jlReceiver.setText("No user Selected.");
        jPanel1.add(jlReceiver);
        jlReceiver.setBounds(90, 10, 680, 22);

        jlStatus.setForeground(new java.awt.Color(255, 255, 255));
        jlStatus.setText("online");
        jPanel1.add(jlStatus);
        jlStatus.setBounds(90, 35, 45, 16);
        jPanel1.add(jlClose);
        jlClose.setBounds(820, 10, 40, 40);

        jpChat.add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 60);

        getContentPane().add(jpChat);
        jpChat.setBounds(423, 0, 880, 800);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jpContacts.setBackground(new java.awt.Color(255, 255, 255));
        jpContacts.setLayout(null);
        jScrollPane1.setViewportView(jpContacts);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 424, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }
    private int y = 10;
    private EventHandling eventHandling;
    private String name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlDP;
    private javax.swing.JLabel jlReceiver;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JPanel jpChat;
    private javax.swing.JPanel jpContacts;
    private javax.swing.JPanel jpMessages;
    private javax.swing.JScrollPane jspMessages;
    private javax.swing.JTextField jtfMessage;
    // End of variables declaration//GEN-END:variables
}
