/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Timer;

/**
 * Color Scheme
 * Background : 11151c
 * Accent Color : 5fe0d4  95,224,212
 * Second Color : 8,16,31
 */
/**
 *
 * @author gauravpunjabi
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogin = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        jtfMobileNo = new javax.swing.JTextField();
        jlMobileNo = new javax.swing.JLabel();
        jspMobileNo = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jspPassword = new javax.swing.JSeparator();
        jlPassword = new javax.swing.JLabel();
        jbLogin = new javax.swing.JButton();
        jlLogo = new javax.swing.JLabel();
        jpLoading = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                if(loadingCompleted)
                loadingAnimation(g);
                else
                super.paintComponent(g);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(95, 224, 212));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(8, 16, 31));
        jpLogin.setLayout(null);

        jlLogin.setFont(new java.awt.Font("Raleway", 0, 48)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(95, 224, 212));
        jlLogin.setText("Login");
        jpLogin.add(jlLogin);
        jlLogin.setBounds(122, 53, 125, 58);

        jtfMobileNo.setBackground(new java.awt.Color(8, 16, 31));
        jtfMobileNo.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jtfMobileNo.setForeground(new java.awt.Color(95, 224, 212));
        jtfMobileNo.setText("Enter your Username : ");
        jtfMobileNo.setBorder(null);
        jtfMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMobileNoActionPerformed(evt);
            }
        });
        jpLogin.add(jtfMobileNo);
        jtfMobileNo.setBounds(60, 234, 252, 29);

        jlMobileNo.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jlMobileNo.setForeground(new java.awt.Color(95, 224, 212));
        jlMobileNo.setText("Username : ");
        jpLogin.add(jlMobileNo);
        jlMobileNo.setBounds(60, 193, 135, 29);

        jspMobileNo.setBackground(new java.awt.Color(95, 224, 212));
        jspMobileNo.setForeground(new java.awt.Color(95, 224, 212));
        jpLogin.add(jspMobileNo);
        jspMobileNo.setBounds(60, 275, 262, 20);

        jPasswordField1.setBackground(new java.awt.Color(8, 16, 31));
        jPasswordField1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(95, 224, 212));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jpLogin.add(jPasswordField1);
        jPasswordField1.setBounds(60, 380, 260, 40);

        jspPassword.setBackground(new java.awt.Color(95, 224, 212));
        jspPassword.setForeground(new java.awt.Color(95, 224, 212));
        jpLogin.add(jspPassword);
        jspPassword.setBounds(60, 420, 262, 20);

        jlPassword.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jlPassword.setForeground(new java.awt.Color(95, 224, 212));
        jlPassword.setText("Password : ");
        jpLogin.add(jlPassword);
        jlPassword.setBounds(60, 340, 136, 29);

        jbLogin.setFont(new java.awt.Font("Raleway", 0, 26)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(95, 224, 212));
        jbLogin.setText("Login");
        jbLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 224, 212), 1, true));
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        jpLogin.add(jbLogin);
        jbLogin.setBounds(60, 480, 111, 50);

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 380, 600));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mySpaceLogo.png"))); // NOI18N
        getContentPane().add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 788, 594));

        jpLoading.setOpaque(false);

        javax.swing.GroupLayout jpLoadingLayout = new javax.swing.GroupLayout(jpLoading);
        jpLoading.setLayout(jpLoadingLayout);
        jpLoadingLayout.setHorizontalGroup(
            jpLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpLoadingLayout.setVerticalGroup(
            jpLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jpLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void customInit() {
        setSize(788,594);
        setLocationRelativeTo(null);
        this.x = this.getWidth()/2;
        this.y = this.getHeight()/2;
        this.width = this.height = 0;
        this.jpLoading.setForeground(new Color(95,224,212));
        this.setShape(new RoundRectangle2D.Double(0,0,this.getWidth(),this.getHeight(),20,20));
        this.parallaxTimer = new Timer(7, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent ae) {
               parallaxActionPerformed(ae);
           }
        });
        this.loadingTimer = new Timer(3, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                jlLogo.repaint();
            }
        });
    }
    private void loadingAnimation(Graphics g) {
        this.x -= 5;
        this.y -= 5;
        this.width += 10;
        this.height += 10;
        g.setColor(this.getBackground());
        g.fillOval(this.x, this.y, width, height);
        if(this.x <= -200) {
            loadingCompleted = false;
            loadingTimer.stop();
            this.setVisible(false);
        }
    }
    private void parallaxActionPerformed(ActionEvent ae) {
        if(jpLogin.getLocation().x >= 585)
            this.firstPhaseComplete = true;
        if(firstPhaseComplete)
            this.jlLogo.setLocation(this.jlLogo.getLocation().x + 5,this.jlLogo.getLocation().y);
        this.jpLogin.setLocation(this.jpLogin.getLocation().x + 5,this.jpLogin.getLocation().y);
        if(jlLogo.getLocation().x >= -3) {
            parallaxTimer.stop();
            loadingCompleted = true;
            loadingTimer.start();
        }
    }
    private void jtfMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMobileNoActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        parallaxTimer.start();
    }//GEN-LAST:event_jbLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    private Timer parallaxTimer,loadingTimer;
    private boolean firstPhaseComplete = false;
    private boolean loadingCompleted = false;
    private int x,y,width,height;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlMobileNo;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JPanel jpLoading;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JSeparator jspMobileNo;
    private javax.swing.JSeparator jspPassword;
    private javax.swing.JTextField jtfMobileNo;
    // End of variables declaration//GEN-END:variables
}
