package UserInterface.components;


import BackEnd.Wrapper.Message;
import BackEnd.Wrapper.MessageConstants;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gauravpunjabi
 */
public class MessageLabel extends javax.swing.JPanel implements MessageConstants,ComponentConstants{
    
    private Message message;
    private int statusSize = 52;
    /**
     * Creates new form MessageLabel
     */
    public MessageLabel(final Message message) {
        initComponents();
        this.message = message;
        
        jlMessage.setText(message.getMessage());
        jlMessage.setFont(MESSAGE_FONT);
        jlMessage.setForeground(MESSAGE_COLOR_FONT);
        
        if(message.isSender())
            this.setBackground(MESSAGE_COLOR_SENT);
        else
        {
            this.statusSize = 0;
            this.setBackground(MESSAGE_COLOR_RECIEVED);
        }
        this.jlStatus.setVisible(message.isSender());
    }
    
    public void setStatus(int status){
        if(status == MESSAGE_STATUS_READ)
            this.jlStatus.setIcon(READ_LOGO);
        else if(status == MESSAGE_STATUS_DELIVERED)
            this.jlStatus.setIcon(DELIVERED_LOGO);
        else
            this.jlStatus.setIcon(SENT_LOGO);
    }
    
    @Override
    protected void paintComponent(Graphics g)
    {
        g.setColor(this.getBackground());
        g.fillRoundRect(0,0,getWidth(),getHeight(),30,30);
        super.paintComponent(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMessage = new javax.swing.JLabel();
        jlStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 9));

        jlMessage.setFont(new java.awt.Font("Raleway", 0, 20)); // NOI18N
        jlMessage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlMessage.setText("Pakk rha hai yaar");
        add(jlMessage);

        jlStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/read.png"))); // NOI18N
        jlStatus.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jlStatusHierarchyChanged(evt);
            }
        });
        add(jlStatus);
    }// </editor-fold>//GEN-END:initComponents
    public boolean isSender() { return this.message.isSender(); }
    private void jlStatusHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jlStatusHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jlStatusHierarchyChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlMessage;
    private javax.swing.JLabel jlStatus;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public Dimension getSize() {
        return new Dimension((this.jlMessage.getText().length() * 10) + this.statusSize,46);
    }
    public JLabel getMessageLabel() {
        return jlMessage;
    }
}
